Repository codesquad-member-2020/todo-9, pull requests merged in 2020-04, with the labels that each got.

#1 Docs: README.md에 팀원 정보 및 요구사항 기술서, Ground Rule 작성
  README.md
Labels: documentation

#8 [#6] feat: Mock API 생성
  BE/README.md
  BE/src/main/java/kr/codesquad/todo9/api/TodoAPIController.java
  BE/src/main/java/kr/codesquad/todo9/config/JacksonConfig.java
  BE/src/main/java/kr/codesquad/todo9/domain/Board.java
  BE/src/main/java/kr/codesquad/todo9/domain/Card.java
  BE/src/main/java/kr/codesquad/todo9/domain/Column.java
  BE/src/main/java/kr/codesquad/todo9/domain/Log.java
  BE/src/main/java/kr/codesquad/todo9/domain/User.java
Labels: Feature

#42 [#19] feat: mysql connection 설정 및 jasypt로 DB 접속정보 암호화
  BE/src/main/java/kr/codesquad/todo9/config/JasyptConfig.java
  BE/src/main/resources/application-deploy.properties
  BE/src/main/resources/application-develop.properties
  BE/src/main/resources/application-local.properties
Labels: Feature

#41 [FE] 메인 화면 스타일 적용 완료
  FE/.gitignore
  FE/src/style/reset.css
  FE/src/style/style.css
  FE/src/view/index.html
Labels: Feature

#43 [#20] feat: Local 개발환경에서 사용할 H2 database 설정
  BE/src/main/resources/application-local.properties
  BE/src/main/resources/data.sql
  BE/src/main/resources/schema.sql
Labels: Feature

#44 [#34,40] refactor: Log Table 수정
  BE/src/main/resources/schema.sql
Labels: enhancement

#49 [#33] refactor: User가 Profile Image Url을 담을 수 있도록 수정
  BE/src/main/resources/schema.sql
Labels: enhancement

#56 Feature/fe/html css
  FE/src/style/style.css
  FE/src/view/index.html
Labels: Feature

#58 [#21] feat: Jwt 관련 기능을 담당하는 JwtUtils 클래스 생성
  BE/build.gradle
  BE/src/main/java/kr/codesquad/todo9/domain/User.java
  BE/src/main/java/kr/codesquad/todo9/utils/JwtUtils.java
  BE/src/main/resources/application-local.properties
  BE/src/test/java/kr/codesquad/todo9/utils/JwtUtilsTest.java
Labels: Feature

#60 [#59] feat: 기능구현을 위한 Skeleton 코드 작성
  FE/src/ts/activity.ts
  FE/src/ts/column.ts
  FE/src/ts/common/fetchRequest.js
  FE/src/ts/editcolumn.ts
  FE/src/ts/editnote.ts
  FE/src/ts/index.ts
  FE/src/ts/lib/util.js
  FE/src/ts/view.ts
Labels: FE 리뷰요청

#57 [#55] 런타임 빌드를 위한 파일 수정
  FE/package.json
  FE/src/view/index.html
  FE/webpack.config.js
Labels: FE 리뷰요청

#61 [#22] feat: 기본으로 가지고 있을 데이터 쿼리 작성
  BE/src/main/resources/data.sql
  BE/src/main/resources/schema.sql
Labels: Feature

#64 [#24] feat: login API 구현
  BE/src/main/java/kr/codesquad/todo9/api/TodoAPIController.java
  BE/src/main/java/kr/codesquad/todo9/responseobjects/Result.java
Labels: Feature

#65 [#45] docs: PR template, Issue template 생성
  .github/ISSUE_TEMPLATE/-be--title.md
  .github/ISSUE_TEMPLATE/-fe--title.md
  .github/ISSUE_TEMPLATE/-ios--title.md
  .github/ISSUE_TEMPLATE/-team--title.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Team, documentation

#63 [FE] 컬럼, 카드 랜더하는 메소드 작성
  FE/src/style/style.css
  FE/src/ts/column.ts
  FE/src/ts/common/constants.js
  FE/src/ts/index.ts
  FE/src/view/index.html
  FE/webpack.config.js
Labels: Feature

#71 배포를 위한 Pull Request입니다.
  .github/ISSUE_TEMPLATE/-be--title.md
  .github/ISSUE_TEMPLATE/-fe--title.md
  .github/ISSUE_TEMPLATE/-ios--title.md
  .github/ISSUE_TEMPLATE/-team--title.md
  .github/PULL_REQUEST_TEMPLATE.md
  BE/build.gradle
  BE/src/main/java/kr/codesquad/todo9/api/TodoAPIController.java
  BE/src/main/java/kr/codesquad/todo9/config/JasyptConfig.java
  BE/src/main/java/kr/codesquad/todo9/domain/User.java
  BE/src/main/java/kr/codesquad/todo9/responseobjects/Result.java
  BE/src/main/java/kr/codesquad/todo9/utils/JwtUtils.java
  BE/src/main/resources/application-deploy.properties
  BE/src/main/resources/application-develop.properties
  BE/src/main/resources/application-local.properties
  BE/src/main/resources/data.sql
  BE/src/main/resources/schema.sql
  BE/src/test/java/kr/codesquad/todo9/utils/JwtUtilsTest.java
  FE/.gitignore
  FE/babel.config.js
  FE/package-lock.json
  FE/package.json
  FE/src/style/edit-column.css
  FE/src/style/edit-note.css
  FE/src/style/reset.css
  FE/src/style/style.css
  FE/src/ts/activity.ts
  FE/src/ts/column.ts
  FE/src/ts/common/constants.js
  FE/src/ts/common/fetchRequest.js
  FE/src/ts/editcolumn.ts
  FE/src/ts/editnote.ts
  FE/src/ts/index.ts
  FE/src/ts/lib/util.js
  FE/src/ts/modal.ts
  FE/src/ts/view.ts
  FE/src/view/index.html
  FE/tsconfig.json
  FE/webpack.config.js
Labels: Deploy

#74 [#66] refactor: 요청 경로 변경
  BE/src/main/java/kr/codesquad/todo9/api/TodoAPIController.java
  BE/src/main/java/kr/codesquad/todo9/api/TodoMockAPIController.java
Labels: enhancement

#75 [Deploy] 현재까지 작업 사항을 배포합니다.
  BE/src/main/java/kr/codesquad/todo9/api/TodoAPIController.java
  BE/src/main/java/kr/codesquad/todo9/api/TodoMockAPIController.java
  BE/src/main/java/kr/codesquad/todo9/domain/Board.java
  BE/src/main/java/kr/codesquad/todo9/domain/Card.java
  BE/src/main/java/kr/codesquad/todo9/domain/Column.java
  BE/src/main/java/kr/codesquad/todo9/domain/Log.java
  BE/src/main/java/kr/codesquad/todo9/domain/User.java
  BE/src/main/java/kr/codesquad/todo9/repository/BoardRepository.java
  BE/src/main/java/kr/codesquad/todo9/repository/UserRepository.java
  BE/src/main/resources/data.sql
  BE/src/main/resources/schema.sql
Labels: Deploy

#77 [HotFix] fix: fix Compile Error
  BE/src/main/java/kr/codesquad/todo9/domain/User.java
Labels: bug

#78 [HotFix] Fix Compile Error
  BE/src/main/java/kr/codesquad/todo9/domain/User.java
Labels: bug

#81 [#25] feat: card 생성 API 구현
  BE/src/main/java/kr/codesquad/todo9/api/TodoAPIController.java
  BE/src/main/java/kr/codesquad/todo9/domain/Board.java
Labels: Feature

#84 [#83] refactor: board API Logs 역순정렬 후 반환하도록 수정
  BE/src/main/java/kr/codesquad/todo9/api/TodoAPIController.java
Labels: enhancement

#85 [#26] feat: boardKey에 해당하는 log 객체를 반환하는 API 구현
  BE/src/main/java/kr/codesquad/todo9/api/TodoAPIController.java
Labels: Feature

#87 [#13] 카드 추가 기능 완료
  FE/src/style/style.css
  FE/src/ts/column.ts
  FE/src/ts/columnTemplate.ts
  FE/src/ts/common/configs.ts
  FE/src/ts/common/constants.js
  FE/src/ts/index.ts
  FE/src/view/index.html
Labels: Feature

#88 [#82] 웹팩 추가 설정 완료
  FE/package-lock.json
  FE/package.json
  FE/src/ts/column.ts
  FE/webpack.config.js
Labels: Feature

#96 [#28] feat: Card 수정 API 구현
  BE/src/main/java/kr/codesquad/todo9/api/TodoAPIController.java
  BE/src/main/java/kr/codesquad/todo9/domain/Board.java
  BE/src/main/java/kr/codesquad/todo9/domain/Log.java
Labels: Feature

#100 [#29] card 삭제 API 구현
  BE/src/main/java/kr/codesquad/todo9/api/TodoAPIController.java
  BE/src/main/java/kr/codesquad/todo9/domain/Board.java
Labels: Feature, enhancement

#102 [Deploy] 2020-04-14 Deploy
  BE/src/main/java/kr/codesquad/todo9/api/TodoAPIController.java
  BE/src/main/java/kr/codesquad/todo9/domain/Board.java
Labels: Deploy

#106 [#105] fix: Cors-Error가 DELETE에서 발생하는 이슈 수정
  BE/src/main/java/kr/codesquad/todo9/config/WebConfig.java
Labels: bug

#107 [Deploy] 2020-04-14 Deploy
  BE/src/main/java/kr/codesquad/todo9/api/TodoAPIController.java
  BE/src/main/java/kr/codesquad/todo9/api/TodoMockAPIController.java
  BE/src/main/java/kr/codesquad/todo9/config/WebConfig.java
  BE/src/main/java/kr/codesquad/todo9/requestobject/ContentsObject.java
  BE/src/main/java/kr/codesquad/todo9/responseobject/Result.java
Labels: Deploy

#110 [#105] fix: Cors-Error가 DELETE에서 발생하는 이슈 수정
  BE/src/main/java/kr/codesquad/todo9/config/WebConfig.java
Labels: bug

#113 [#112] refactor: Edit Card API 요청 객체 수정
  BE/src/main/java/kr/codesquad/todo9/api/TodoAPIController.java
Labels: enhancement

#115 [FE] 칼럼 내 이동, 마크업 데이터셋 추가
  FE/src/style/style.css
  FE/src/ts/column.ts
  FE/src/ts/columnTemplate.ts
  FE/src/ts/index.ts
  FE/src/ts/lib/util.js
Labels: Feature

#118 [#30] feat: 카드 이동 API 생성
  BE/src/main/java/kr/codesquad/todo9/api/TodoAPIController.java
  BE/src/main/java/kr/codesquad/todo9/domain/Board.java
  BE/src/main/java/kr/codesquad/todo9/requestobject/MoveCardObject.java
Labels: Feature

#122 [FE] 카드 이동 기능 (drag and drop api 사용)
  FE/src/style/style.css
  FE/src/ts/column.ts
  FE/src/ts/moveCard.ts
Labels: Feature

#125 [Deploy] 2020-04-15 Deploy
  BE/src/main/java/kr/codesquad/todo9/api/TodoAPIController.java
  BE/src/main/java/kr/codesquad/todo9/config/WebMvcConfig.java
  BE/src/main/java/kr/codesquad/todo9/domain/Board.java
  BE/src/main/java/kr/codesquad/todo9/interceptor/AuthInterceptor.java
  BE/src/main/java/kr/codesquad/todo9/requestobject/ContentsObject.java
  BE/src/main/java/kr/codesquad/todo9/requestobject/MoveCardObject.java
  BE/src/main/java/kr/codesquad/todo9/utils/JwtUtils.java
  FE/src/style/style.css
  FE/src/ts/column.ts
  FE/src/ts/columnTemplate.ts
  FE/src/ts/editnote.ts
  FE/src/ts/index.ts
  FE/src/ts/lib/util.js
  FE/src/ts/moveCard.ts
  FE/src/ts/tododatamodel.ts
Labels: Deploy

#127 [FE] 로그인 화면 중간 PR [메인 화면 실행 안됨]
  FE/package-lock.json
  FE/package.json
  FE/src/style/login.css
  FE/src/ts/column.ts
  FE/src/ts/common/configs.ts
  FE/src/ts/index.ts
  FE/src/ts/login.ts
  FE/webpack.config.js
Labels: Feature

#129 [Deploy] 2020-04-15 Deploy
  BE/src/main/java/kr/codesquad/todo9/api/CardAPIController.java
  BE/src/main/java/kr/codesquad/todo9/api/LogAPIController.java
  BE/src/main/java/kr/codesquad/todo9/api/TodoAPIController.java
  BE/src/main/java/kr/codesquad/todo9/api/TodoMockAPIController.java
  BE/src/main/java/kr/codesquad/todo9/api/UserAPIController.java
  BE/src/main/java/kr/codesquad/todo9/domain/Board.java
  BE/src/main/java/kr/codesquad/todo9/domain/User.java
  BE/src/main/java/kr/codesquad/todo9/dto/LogDTO.java
  BE/src/main/java/kr/codesquad/todo9/interceptor/AuthInterceptor.java
  BE/src/main/java/kr/codesquad/todo9/repository/LogRepository.java
  FE/package-lock.json
  FE/package.json
  FE/src/style/login.css
  FE/src/ts/column.ts
  FE/src/ts/common/configs.ts
  FE/src/ts/index.ts
  FE/src/ts/login.ts
  FE/webpack.config.js
Labels: Deploy

#134 [#133] fix: cors issue 해결
  BE/src/main/java/kr/codesquad/todo9/interceptor/AuthInterceptor.java
  BE/src/main/java/kr/codesquad/todo9/interceptor/SimpleCorsFilter.java
Labels: bug

#135 [Deploy] 2020-04-16 Deploy
  BE/src/main/java/kr/codesquad/todo9/interceptor/AuthInterceptor.java
  BE/src/main/java/kr/codesquad/todo9/interceptor/SimpleCorsFilter.java
Labels: Deploy

#130 [FE] [CORS 에러] (POST 요청) 로그인 기능 완료
  FE/src/style/login.css
  FE/src/ts/column.ts
  FE/src/ts/common/configs.ts
  FE/src/ts/common/fetchRequest.js
  FE/src/ts/editnote.ts
  FE/src/ts/index.ts
  FE/src/ts/login.ts
Labels: Feature

#138 [#137] refactor: Board 요청시 Log가 더 상세한 정보를 포함하도록 변경
  BE/src/main/java/kr/codesquad/todo9/api/TodoAPIController.java
  BE/src/main/java/kr/codesquad/todo9/dto/BoardDTO.java
Labels: enhancement

#139 [Deploy] 2020-04-16 Deploy
  BE/src/main/java/kr/codesquad/todo9/api/TodoAPIController.java
  BE/src/main/java/kr/codesquad/todo9/dto/BoardDTO.java
  FE/src/style/activity.css
  FE/src/style/login.css
  FE/src/ts/activity.ts
  FE/src/ts/column.ts
  FE/src/ts/common/configs.ts
  FE/src/ts/common/fetchRequest.js
  FE/src/ts/common/usercardaction.ts
  FE/src/ts/editnote.ts
  FE/src/ts/index.ts
  FE/src/ts/login.ts
Labels: Deploy

#144 [#143] fix: log 객체가 다른 정보를 리턴하는 오류 수정
  BE/src/main/java/kr/codesquad/todo9/domain/Board.java
Labels: bug

#145 [Deploy] 2020-04-16 deploy
  BE/src/main/java/kr/codesquad/todo9/domain/Board.java
  FE/src/style/activity.css
  FE/src/ts/activity.ts
  FE/src/ts/column.ts
  FE/src/ts/common/configs.ts
  FE/src/ts/common/fetchRequest.js
  FE/src/ts/editnote.ts
Labels: Deploy

#147 [#146] feature: 젤로가 요청하신 Card가 더 많은 정보를 담도록 기능 추가
  BE/src/main/java/kr/codesquad/todo9/api/TodoAPIController.java
  BE/src/main/java/kr/codesquad/todo9/dto/BoardDTO.java
  BE/src/main/java/kr/codesquad/todo9/dto/CardDTO.java
  BE/src/main/java/kr/codesquad/todo9/dto/ColumnDTO.java
  BE/src/main/java/kr/codesquad/todo9/repository/CardRepository.java
Labels: Feature

#148 [Deploy] 2020-04-16 Deploy
  BE/src/main/java/kr/codesquad/todo9/api/TodoAPIController.java
  BE/src/main/java/kr/codesquad/todo9/dto/BoardDTO.java
  BE/src/main/java/kr/codesquad/todo9/dto/CardDTO.java
  BE/src/main/java/kr/codesquad/todo9/dto/ColumnDTO.java
  BE/src/main/java/kr/codesquad/todo9/repository/CardRepository.java
Labels: Deploy

#153 [#150] refactor: card move 로직을 서버에서 제대로 처리하도록 수정
  BE/src/main/java/kr/codesquad/todo9/domain/Board.java
Labels: enhancement

#154 [Deploy] 2020-04-16 배포
  BE/src/main/java/kr/codesquad/todo9/domain/Board.java
Labels: Deploy

#155 [#150] refactor: card move 로직을 서버에서 제대로 처리하도록 수정
  BE/src/main/java/kr/codesquad/todo9/domain/Board.java
  BE/src/main/resources/data.sql
Labels: bug, enhancement

#156 [Deploy] 2020-04-16 오늘의 마지막 배포
  BE/src/main/java/kr/codesquad/todo9/domain/Board.java
  BE/src/main/resources/data.sql
Labels: Deploy

#150 [FE] 카드 이동 - 버그 해결 / 서버 통신 기능 완료
  FE/src/ts/column.ts
  FE/src/ts/common/configs.ts
  FE/src/ts/common/confirmMessage.js
  FE/src/ts/common/constants.js
  FE/src/ts/moveCard.ts
Labels: Feature

#162 [#161] fix: 삭제된 카드가 보이지 않도록 수정
  BE/src/main/java/kr/codesquad/todo9/api/TodoAPIController.java
Labels: bug

#165 [#164] refactor: 프론트쪽 입력 핸들링을 하지 않도록 수정
  BE/src/main/java/kr/codesquad/todo9/domain/Board.java
Labels: enhancement

#123 [FE][리뷰요청용] 카드 이동 기능 (drag and drop api 사용)
  FE/src/style/style.css
  FE/src/ts/column.ts
  FE/src/ts/moveCard.ts
Labels: FE 리뷰요청, Feature

#168 [FE] 2주차 리뷰 요청
  .gitignore
  babel.config.js
  package-lock.json
  package.json
  src/style/activity.css
  src/style/edit-column.css
  src/style/edit-note.css
  src/style/login.css
  src/style/reset.css
  src/style/style.css
  src/ts/activity.ts
  src/ts/column.ts
  src/ts/columnTemplate.ts
  src/ts/common/configs.ts
  src/ts/common/confirmMessage.js
  src/ts/common/constants.js
  src/ts/common/fetchRequest.js
  src/ts/common/usercardaction.ts
  src/ts/editcolumn.ts
  src/ts/editnote.ts
  src/ts/index.ts
  src/ts/lib/util.js
  src/ts/login.ts
  src/ts/modal.ts
  src/ts/moveCard.ts
  src/ts/updateDataset.ts
  src/ts/view.ts
  src/view/index.html
  tsconfig.json
  webpack.config.js
Labels: FE 리뷰요청
